const randomSypnopsis = [
  "The story of a girl named Alice who falls down a rabbit hole into a fantasy world populated by peculiar and anthropomorphic creatures. The tale is filled with allusions to Dodgson's friends. The tale plays with logic in ways that have given the story lasting popularity with adults as well as children. It is considered to be one of the most characteristic examples of the genre of literary nonsense, and its narrative course and structure have been enormously influential, especially in the fantasy genre. ",
  "The year is 2320. Andi Lloyd is content with her life as the assistant to her adoptive father, a starship doctor, but her secure world turns upside down when she begins uncovering secrets from her past. When her father mysteriously starts losing his mind, she finds that she can no longer count on him to guide or help her. With mutiny breaking out on the ship, and two factions desperate for a valuable secret she holds, she must race to help her father and herself before time runs out.",
  "The main character, Emma Woodhouse, is described in the opening paragraph as ''handsome, clever, and rich'' but is also rather spoiled. As a result of the recent marriage of her former governess, Emma prides herself on her ability to matchmake, and proceeds to take under her wing an illegitimate orphan, Harriet Smith, whom she hopes to marry off to the vicar, Mr Elton. So confident is she that she persuades Harriet to reject a proposal from a young farmer who is a much more suitable partner for the girl.",
  "Eight years ago, Anne Elliot fell in love with poor but ambitious naval officer Captain Frederick Wentworth -- a choice which Anne's family was dissatisfied with. Lady Russell, friend and mentor to Anne, persuaded the younger woman to break off the match; now, on the verge of spinsterhood, Anne re-encounters Frederick Wentworth as he courts her spirited young neighbour, Louisa Musgrove. ",
  "Fanny Price, young and from a poor family, is raised by her rich uncle and aunt at Mansfield Park. She grows up with her four cousins but is always treated as an inferior; only her cousin Edmund shows any real kindness. Over time, Fanny's gratitude towards Edmund grows into a secret, romantic love",
  "Sent to investigate mysterious encounters that are disrupting international shipping, Professor Aronnax, his servant Conseil, and disgruntled harpooner Ned Land are captured when their frigate is sunk during an encounter with the monster. The submarine Nautilus and its eccentric Captain Nemo afford the professor and his companions endless fascination and danger as they're swept along on a yearlong undersea voyage.",
  "Phileas Fogg of London and his newly employed valet Passepartout attempt to circumnavigate the globe in just 80 days to win a £20,000 wager set by members of the Reform Club. (An unabridged reproduction of the original 1873 Hetzel edition.)",
  "On an expedition to Antarctica, Professor William Dyer and his colleagues discover the remains of ancient half-vegetable, half-animal life-forms. The extremely early date in the geological strata is surprising because of the highly-evolved features found in these previously unkown life-forms. Through a series of dark revelations, violent episodes, and misunderstandings, the group learns of Earth's secret history and legacy.",
  "The sacrifices made to secure The Source will be in vain if the scientist who spearheaded the original effort to stop The Pandemic can't be found. The invasion of America has begun and foreign soldiers are willing to tear the country apart to find him. Cooper Braaten's Navy SEALs race to secure the virologist and his critical research but it will take all their skills and more than a little luck to succeed when Apache Dawn is declared.",
  "The creepy short story prequel to the 'Ghost Hunter' series of novels! Malachi Hunter's abiding passion for the occult and supernatural has made him a loner and social misfit. Unfortunately, his lack of self-confidence has always prevented him from fulfilling his ambition to become a ghost hunter. That is until he meets Anna Spalding. In a misguided effort to impress her, he agrees to investigate a property managed by her father's letting agency. His investigation has consequences that none of them could have anticipated..",
  "When Lanzarote anti-corruption activist Celestino is T-boned on a lonely road, he knows the collision was no accident. Wounded and fearing for his life, he hides in an abandoned fishing village, waiting for a chance to make it home. Meanwhile, his wife Paula is distraught and sets out to look for him. Paula's search for her husband quickly descends into mayhem, danger and intrigue. Before long, she realizes she’s being followed. She needs answers, and fast.",
  "With only the telegram to guide him, 12-year-old Tommy Mooney arms himself to the hilt: with a sling-shot, a boomerang, a bow and arrow set, and an indomitable sense of youthful optimism. Mounting his Schwinn bicycle, he heads for the Brooklyn Harbor, setting a course for London, England, where he plans to recruit Jack's British fiancée before continuing on to Nazi-occupied Belgium.",
  "Thus begins a journey that one reader calls, 'A rattling, high concept, wartime adventure--with a wonderfully quirky and incredibly brave hero-narrator. Soon enough, hope turns to foreboding--as it begins to look as though Tommy is being deceived by the Gestapo, used in a plot to expose a Resistance network created to help downed airmen. ' Bravery, he realizes, is like teeth plaque. It takes time to build up.",
  "The totalitarian Free Earth, led by the populist Brother Lin, has also lost a ship on this lane, and is intent on finding out why. The Company wants their cargo delivered and can make Inez's life very difficult if she doesn't succeed. With the nearest waystation three days away, death in the cold vacuum of space is a distinct possibility as well.",
  "When Kellan Ayrwick returns home for his father's retirement, he finds a body in Diamond Hall's stairwell. Unfortunately, Kellan has a connection to the victim, and so do several members of his family. Soon after, the college's athletic program receives mysterious donations, a nasty blog denounces his father, and someone attempts to change students' grades. Something is amiss on campus, but none of the facts add up.With the help of his eccentric nana, Kellan tries to stay out of the sheriff's way and solve the mystery. But can they find the killer before he strikes again?",
  "Five men who share one major flaw: an appetite for mistresses. Infallible is about five gamers in their late thirties who come together every Thursday night for a John Madden Football tournament. This weekly event is hosted and narrated by an older guy they refer to as Uncle Glenn - the sixth member of the Madden Night crew. Once Uncle Glenn’s wife departs for her regular Thursday night shift, the crew arrives to smoke the most potent weed in New Orleans, roast each other into knee-slapping laughter, and swap strategies of how to cheat and not get caught. Uncle Glenn loves their company, even though he’s happily married and faithful to his wife, Diana",
  "As Queen Gurtie mourns her husband's death, she finds an unexpected friend in the new general's wife, Emma. But will this country belle adapt to palace life or become a burden?Eyric's enigmatic 'grandfather' has asked her to learn the ropes of ruling the island. But meeting the island's mysterious Putlag is beginning to sound dangerous. Legends of this shadow ruler abound. Are any of them true? If she chooses to proceed, will she want to forget what she discovers?",
];


module.exports = randomSypnopsis
